### ISSUE TITLE
version problem 

### ISSUE THREAD

**Issue by abdalla209** [mathworks/electric-all-terrain-vehicle#1]
Hi , can you please a upload a matlab 2019a version

**Comment by veeralakshendra** [comment]
Hello,

Thanks for your comments. Please check out this MATLAB Answer, and try the accepted answer: https://www.mathworks.com/matlabcentral/answers/429729-opening-a-simulink-file-that-was-saved-in-r2018b-version-onto-a-r2017b-version
In case you are not able to open the model in previous version please reach out to us at racinglounge@mathworks.com

**Comment by THEGODOFWAR12355** [comment]
greetings sir, I downloaded the model and opened it in 2020a and then used it as reference to build the same model with the same parameters for every block except for the PID controller block (Every other block was inserted from the 2020a library and the parameters were set identically to your model), but it seems the model is not working and the velocity is not tracing the supplied signal as it should , there is a image of the scope observations attached to this comment please solve my query
![Screenshot (92)](https://user-images.githubusercontent.com/69871445/99142902-52653a80-267f-11eb-9b8f-a0d4624f45ef.png)

**Comment by veeralakshendra** [comment]
> greetings sir, I downloaded the model and opened it in 2020a and then used it as reference to build the same model with the same parameters for every block except for the PID controller block (Every other block was inserted from the 2020a library and the parameters were set identically to your model), but it seems the model is not working and the velocity is not tracing the supplied signal as it should , there is a image of the scope observations attached to this comment please solve my query
> ![Screenshot (92)](https://user-images.githubusercontent.com/69871445/99142902-52653a80-267f-11eb-9b8f-a0d4624f45ef.png)

**Comment by veeralakshendra** [comment]
Hi,
Thanks for reaching out and going through the content. There might be some issue with certain parameters and solver settings. Could you send your model at racinglounge@mathworks.com? We will have a look and will try to resolve the issues.
Regards,
Veer Alakshendra
MathWorks

**Comment by veeralakshendra** [comment]
We received the files from THEGODOFWAR12355 on racinglounge@mathworks.com and the issue was with the model parameters and the gear shaft was running in the opposite direction. Now, the issue has been resolved. 
Please reach out to us at racinglounge@mathworks.com in case you are facing some issues with your customized model.
